"""Install the in-gateway hook package under ``$HERMES_HOME/hooks/``.

``hermes-flight-recorder install`` calls :func:`install_hook`. It writes a
``HOOK.yaml`` manifest and a generated, standard-library-only ``handler.py``.
The handler appends events to the Flight Recorder spool; it imports nothing from this
package, so it runs in whatever Python environment the Hermes gateway uses.
The Flight Recorder home is baked into the handler at install time (a ``$SC_HERMES_FLIGHT_RECORDER_HOME``
environment variable overrides it at runtime).

The hook package is the only write Flight Recorder ever makes into the Hermes home.
"""

from __future__ import annotations

import json
from pathlib import Path

from ...version import build_identity
from ..atomic_file import atomic_write
from . import (
    ERRLOG_FILENAME,
    HOOK_DIR_NAME,
    HOOK_EVENTS,
    MAX_ERRLOG_BYTES,
    MAX_SPOOL_BYTES,
    SPOOL_FILENAME,
)

_MANIFEST = (
    f"name: {HOOK_DIR_NAME}\n"
    "description: Hermes Flight Recorder — live lifecycle capture.\n"
    "events:\n" + "".join(f"  - {event}\n" for event in HOOK_EVENTS)
)

# The generated handler. Only the @@TOKENS@@ are substituted (with valid
# Python literals), so the JSON/`%`-formatting braces below stay untouched.
_HANDLER_TEMPLATE = '''\
# Auto-generated by `hermes-flight-recorder install`. Do not edit by hand.
#
# In-gateway spooler for the Hermes Flight Recorder. Standard library only:
# it appends one JSON line per Hermes lifecycle event to the Flight Recorder spool and
# never raises into the gateway. All mapping, encryption, and producer_sequence
# assignment happen Flight Recorder-side in `hermes-flight-recorder run` (the drain).
import json
import os
import time
import uuid

_BAKED_SC_HERMES_FLIGHT_RECORDER_HOME = @@BAKED@@
_FLIGHT_RECORDER_BUILD = @@BUILD@@
_SPOOL_FILENAME = @@SPOOL@@
_ERRLOG_FILENAME = @@ERRLOG@@
_MAX_SPOOL_BYTES = @@MAXBYTES@@
_MAX_ERRLOG_BYTES = @@MAXERRBYTES@@


def _flight_recorder_home():
    return os.environ.get("SC_HERMES_FLIGHT_RECORDER_HOME") or _BAKED_SC_HERMES_FLIGHT_RECORDER_HOME


def _log_error(message):
    try:
        path = os.path.join(_flight_recorder_home(), _ERRLOG_FILENAME)
        data = ("%f %s\\n" % (time.time(), message)).encode("utf-8", "replace")
        if len(data) > _MAX_ERRLOG_BYTES:
            data = data[: _MAX_ERRLOG_BYTES - 1] + b"\\n"
        try:
            size = os.path.getsize(path)
        except OSError:
            size = 0
        if size + len(data) > _MAX_ERRLOG_BYTES:
            os.replace(path, path + ".1")
        with open(path, "ab") as fh:
            fh.write(data)
    except Exception:
        pass


def _metadata_context(event_type, context):
    # Hermes truncates agent message/response bodies before hooks see them.
    # Do not persist that misleading preview in the spool; state.db is the
    # encrypted, durable content source on the Flight Recorder side.
    if not isinstance(context, dict):
        return context
    metadata = dict(context)
    if event_type in ("agent:start", "agent:end"):
        metadata.pop("message", None)
    if event_type == "agent:end":
        metadata.pop("response", None)
    return metadata


def handle(event_type, context):
    # Never raise into Hermes. The gateway swallows handler errors, but we also
    # want a Flight Recorder-side record when capture fails.
    try:
        home = _flight_recorder_home()
        spool = os.path.join(home, _SPOOL_FILENAME)
        line = json.dumps(
            {
                "spool_event_id": uuid.uuid4().hex,
                "event_type": event_type,
                "context": _metadata_context(event_type, context),
                "captured_at": time.time(),
            },
            ensure_ascii=False, separators=(",", ":"), default=str,
        )
        os.makedirs(home, exist_ok=True)
        fd = os.open(spool, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o600)
        try:
            os.write(fd, (line + "\\n").encode("utf-8"))
        finally:
            os.close(fd)
    except Exception as exc:
        _log_error("handler error on %r: %r" % (event_type, exc))
'''


def render_handler(
    flight_recorder_home: str | Path, *, build: str | None = None
) -> str:
    """Return the handler source with the Flight Recorder home and constants baked in."""
    baked = str(Path(flight_recorder_home).expanduser().resolve())
    installed_build = build or build_identity()
    return (
        _HANDLER_TEMPLATE.replace("@@BAKED@@", json.dumps(baked))
        .replace("@@BUILD@@", json.dumps(installed_build))
        .replace("@@SPOOL@@", json.dumps(SPOOL_FILENAME))
        .replace("@@ERRLOG@@", json.dumps(ERRLOG_FILENAME))
        .replace("@@MAXBYTES@@", str(MAX_SPOOL_BYTES))
        .replace("@@MAXERRBYTES@@", str(MAX_ERRLOG_BYTES))
    )


def baked_flight_recorder_home(hook_dir: str | Path) -> str | None:
    """Return the Flight Recorder home baked into an installed ``handler.py``.

    Reads the ``_BAKED_SC_HERMES_FLIGHT_RECORDER_HOME = <json>`` line the
    generator writes, so ``install`` can verify the hook targets the intended
    recorder root. Returns None if the file or the line is absent/unreadable.
    """
    handler = Path(hook_dir) / "handler.py"
    try:
        text = handler.read_text(encoding="utf-8")
    except OSError:
        return None
    marker = "_BAKED_SC_HERMES_FLIGHT_RECORDER_HOME = "
    for line in text.splitlines():
        if line.startswith(marker):
            try:
                return json.loads(line[len(marker):])
            except ValueError:
                return None
    return None


def baked_flight_recorder_build(hook_dir: str | Path) -> str | None:
    """Return the package build identity baked into the installed handler."""
    handler = Path(hook_dir) / "handler.py"
    try:
        text = handler.read_text(encoding="utf-8")
    except OSError:
        return None
    marker = "_FLIGHT_RECORDER_BUILD = "
    for line in text.splitlines():
        if line.startswith(marker):
            try:
                value = json.loads(line[len(marker):])
            except ValueError:
                return None
            return value if isinstance(value, str) else None
    return None


# The gateway process imports these generated files, so they stay
# world-readable; they hold no secrets (paths and constants only).
_HOOK_FILE_MODE = 0o644


def install_hook(
    hermes_home: str | Path,
    flight_recorder_home: str | Path,
    *,
    force: bool = False,
    build: str | None = None,
) -> Path:
    """Write the hook package under ``$HERMES_HOME/hooks/hermes-flight-recorder``.

    Raises :class:`FileExistsError` (with the hook dir as its argument) when
    the package already exists and ``force`` is false. Returns the hook dir.
    """
    hook_dir = Path(hermes_home).expanduser() / "hooks" / HOOK_DIR_NAME
    if hook_dir.exists() and not force:
        raise FileExistsError(str(hook_dir))
    hook_dir.mkdir(parents=True, exist_ok=True)
    atomic_write(
        hook_dir / "HOOK.yaml", _MANIFEST.encode("utf-8"), mode=_HOOK_FILE_MODE
    )
    atomic_write(
        hook_dir / "handler.py",
        render_handler(flight_recorder_home, build=build).encode("utf-8"),
        mode=_HOOK_FILE_MODE,
    )
    return hook_dir
