"""Install the in-gateway hook package under ``$HERMES_HOME/hooks/``.

``hermes-flight-recorder init`` calls :func:`install_hook`. It writes a
``HOOK.yaml`` manifest and a generated, standard-library-only ``handler.py``.
The handler appends events to the Flight Recorder spool; it imports nothing from this
package, so it runs in whatever Python environment the Hermes gateway uses.
The Flight Recorder home is baked into the handler at install time (a ``$SC_HERMES_FLIGHT_RECORDER_HOME``
environment variable overrides it at runtime).

The hook package is the only write Flight Recorder ever makes into the Hermes home.
"""

from __future__ import annotations

import json
from pathlib import Path

from . import ERRLOG_FILENAME, HOOK_DIR_NAME, HOOK_EVENTS, SPOOL_FILENAME

# Soft cap on the spool. Past it the handler drops the new event rather than
# block the gateway; the reconciler still catches the loss against state.db.
MAX_SPOOL_BYTES = 64 * 1024 * 1024  # 64 MiB

_MANIFEST = (
    f"name: {HOOK_DIR_NAME}\n"
    "description: Hermes Flight Recorder — live lifecycle capture.\n"
    "events:\n" + "".join(f"  - {event}\n" for event in HOOK_EVENTS)
)

# The generated handler. Only the @@TOKENS@@ are substituted (with valid
# Python literals), so the JSON/`%`-formatting braces below stay untouched.
_HANDLER_TEMPLATE = '''\
# Auto-generated by `hermes-flight-recorder init`. Do not edit by hand.
#
# In-gateway spooler for the Hermes Flight Recorder. Standard library only:
# it appends one JSON line per Hermes lifecycle event to the Flight Recorder spool and
# never raises into the gateway. All mapping, encryption, and producer_sequence
# assignment happen Flight Recorder-side in `hermes-flight-recorder run` (the drain).
import json
import os
import time

_BAKED_SC_HERMES_FLIGHT_RECORDER_HOME = @@BAKED@@
_SPOOL_FILENAME = @@SPOOL@@
_ERRLOG_FILENAME = @@ERRLOG@@
_MAX_SPOOL_BYTES = @@MAXBYTES@@


def _flight_recorder_home():
    return os.environ.get("SC_HERMES_FLIGHT_RECORDER_HOME") or _BAKED_SC_HERMES_FLIGHT_RECORDER_HOME


def _log_error(message):
    try:
        with open(os.path.join(_flight_recorder_home(), _ERRLOG_FILENAME), "a", encoding="utf-8") as fh:
            fh.write("%f %s\\n" % (time.time(), message))
    except Exception:
        pass


def _metadata_context(event_type, context):
    # Hermes truncates agent message/response bodies before hooks see them.
    # Do not persist that misleading preview in the spool; state.db is the
    # encrypted, durable content source on the Flight Recorder side.
    if not isinstance(context, dict):
        return context
    metadata = dict(context)
    if event_type == "agent:start":
        metadata.pop("message", None)
    elif event_type == "agent:end":
        metadata.pop("response", None)
    return metadata


def handle(event_type, context):
    # Never raise into Hermes. The gateway swallows handler errors, but we also
    # want a Flight Recorder-side record when capture fails.
    try:
        home = _flight_recorder_home()
        spool = os.path.join(home, _SPOOL_FILENAME)
        try:
            if os.path.getsize(spool) > _MAX_SPOOL_BYTES:
                _log_error("spool over cap; dropped %s" % event_type)
                return
        except OSError:
            pass  # spool does not exist yet
        line = json.dumps(
            {
                "event_type": event_type,
                "context": _metadata_context(event_type, context),
                "captured_at": time.time(),
            },
            ensure_ascii=False, separators=(",", ":"), default=str,
        )
        os.makedirs(home, exist_ok=True)
        fd = os.open(spool, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o600)
        try:
            os.write(fd, (line + "\\n").encode("utf-8"))
        finally:
            os.close(fd)
    except Exception as exc:
        _log_error("handler error on %r: %r" % (event_type, exc))
'''


def render_handler(flight_recorder_home: str | Path) -> str:
    """Return the handler source with the Flight Recorder home and constants baked in."""
    baked = str(Path(flight_recorder_home).expanduser().resolve())
    return (
        _HANDLER_TEMPLATE.replace("@@BAKED@@", json.dumps(baked))
        .replace("@@SPOOL@@", json.dumps(SPOOL_FILENAME))
        .replace("@@ERRLOG@@", json.dumps(ERRLOG_FILENAME))
        .replace("@@MAXBYTES@@", str(MAX_SPOOL_BYTES))
    )


def install_hook(
    hermes_home: str | Path, flight_recorder_home: str | Path, *, force: bool = False
) -> Path:
    """Write the hook package under ``$HERMES_HOME/hooks/hermes-flight-recorder``.

    Raises :class:`FileExistsError` (with the hook dir as its argument) when
    the package already exists and ``force`` is false. Returns the hook dir.
    """
    hook_dir = Path(hermes_home).expanduser() / "hooks" / HOOK_DIR_NAME
    if hook_dir.exists() and not force:
        raise FileExistsError(str(hook_dir))
    hook_dir.mkdir(parents=True, exist_ok=True)
    (hook_dir / "HOOK.yaml").write_text(_MANIFEST, encoding="utf-8")
    (hook_dir / "handler.py").write_text(render_handler(flight_recorder_home), encoding="utf-8")
    return hook_dir
